menu/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^menuapp/', include('menuapp.urls')),
    url(r'^api/', include('menuapp.api_urls')),
]

menuapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^recipe/(?P<recipe_id>\w{0,50})/$', views.recipe, name='recipe'),
    url(r'^add_recipe/$', views.addRecipe, name='add_recipe'),
    url(r'^add_category/$', views.addCategory, name='add_category'),
]

menuapp/models.py
from django.db import models


class Recipe(models.Model):
    title = models.CharField(max_length=255)
    method = models.TextField()
    category = models.ForeignKey('Category', on_delete=models.CASCADE, default=1)
    weeks = models.ManyToManyField('Week')
    ingredients = models.ManyToManyField(
        'Ingredient',
        through='IngredientsRecipes',
        related_name='recipes',
    )

    def __str__(self):
        return self.title

class Ingredient(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class IngredientsRecipes(models.Model):
    recipe = models.ForeignKey('Recipe', on_delete=models.CASCADE)
    ingredient = models.ForeignKey('Ingredient', on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=5, decimal_places=1)
    addinfo = models.CharField(max_length=50, blank=True)
    unit = models.CharField(max_length=10, blank=True)


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Week(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

menuapp/forms.py
from django.forms import ModelForm
from .models import Recipe, Category

# class RecipeForm(ModelForm):
#     class Meta:
#         model = Recipe
#         fields = ('title', 'method', 'ingredients')
        # fields = '__all__'


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

menuapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

from .serializers import RecipeSerializer, CategorySerializer, WeekSerializer
from .models import Recipe, IngredientsRecipes, Category, Week
from django.shortcuts import render

from .forms import  CategoryForm



class RecipeList(APIView):
    def get(self, request):
        week = request.GET.get('week')
        recipes = Recipe.objects.all()
        if week:
            recipes = recipes.filter(weeks__id=week)
        serializer = RecipeSerializer(recipes , many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = RecipeSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)      


class CategoryList(APIView):
    def get(self, request):
        categories = Category.objects.all()
        serializer = CategorySerializer(categories, many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = CategorySerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class WeekList(APIView):
    def get(self, request):
        weeks = Week.objects.all()
        serializer = WeekSerializer(weeks, many=True)
        return Response(serializer.data)


class WeekDetail(APIView):
    def get(self, request, week_id):
        week = Week.objects.get(id=week_id)
        serializer = WeekSerializer(week);
        return Response(serializer.data)


class RecipeDetail(APIView):
    def get(self, request, recipe_id):
        recipe = Recipe.objects.get(id=recipe_id)
        serializer = RecipeSerializer(recipe);
        return Response(serializer.data)

    def put(self, request, recipe_id, format=None):
        recipe = Recipe.objects.get(id=recipe_id)
        data_context = {'week': request.data.get('week', '')}
        serializer = RecipeSerializer(recipe, data=request.data, partial=True, context=data_context)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class RecipRemoveWeek(APIView):

    def put(self, request, recipe_id, format=None):
        recipe = Recipe.objects.get(id=recipe_id)
        data_context = {'week': request.data.get('week', ''), 'remove': True}
        serializer = RecipeSerializer(recipe, data=request.data, partial=True, context=data_context)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

def index(request):
    recipes = Recipe.objects.all()
    context = {
        'recipes': recipes 
    }
    # import ipdb; ipdb.set_trace()
    return render(request, 'index.html', context);


def recipe(request, recipe_id): 
    recipe = Recipe.objects.get(id=recipe_id)

    context = {
        'recipe': recipe
    }
    return render(request, 'recipe.html', context); 


def addRecipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST)
        if form.is_valid():
            recipe = form.save()
            return redirect('index')
    else:
        form = RecipeForm()

    return render(request, 'add_recipe.html', {'form': form})


def addCategory(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            recipe = form.save()
            return redirect('index')
    else:
        form = CategoryForm()

    return render(request, 'add_category.html', {'form': form})

menuapp/templates/add_category.html
{% extends "base.html" %}
{% block content %}
    Add a new category
    <form action="{% url 'add_category' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit" />
    </form>
{% endblock content %}

menuapp/templates/add_recipe.html
{% extends "base.html" %}
{% block content %}
    Add recipe
    <form action="{% url 'add_recipe' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit" />
    </form>
{% endblock content %}

menuapp/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="style.css">
  <title>Menu</title>
</head>
<body>
    {% block content %}{% endblock content %}
    <div class="foo">
      <li></li>
      <li></li>
      <li></li>
      <li></li>
    </div>
</body>
</html>

menuapp/templates/index.html
{% extends "base.html" %}

{% block content %}   
<a href="{% url 'add_recipe' %}">Add a new recipe</a>
<a href="{% url 'add_category' %}">Add a new category</a>
<ul>
{% for recipe in recipes %}
    <li>
        <h2><a href="{% url 'recipe' recipe.id %}">{{ recipe.title }}</a></h2>
        <h3>Ingredients:</h3>
        <ul>
            {% for ingredient in recipe.ingredientsrecipes_set.all %}
                <li>{{ ingredient.ingredient.name }} : {{ ingredient.amount }} {{ ingredient.ingredient.unit }}</li>
            {% endfor %}
        </ul>
        <p>{{ recipe.method }}</p>
        <p><b>Category:</b> {{ recipe.category }}</p>
    </li>
{% endfor %}
</ul>
{% endblock content %}  

menuapp/templates/recipe.html
{% extends "base.html" %}
{% block content %}
    <h2>{{ recipe.title }}</h2>
    <h3>Ingredients:</h3>
    <ul>
        {% for ingredient in recipe.ingredientsrecipes_set.all %}
            <li>{{ ingredient.ingredient.name }} : {{ ingredient.amount }} {{ ingredient.ingredient.unit }}</li>
        {% endfor %}
    </ul>
    <p>{{ recipe.method }}</p>
    <p><b>Category:</b> {{ recipe.category }}</p>
{% endblock content %}